#/* /src/docs/products/products.yaml */
paths:
  /api/proudcts/:
    get:
      summary: Obtiene todos los usuarios
      tags:
        - Users
      responses:
        '200':
          description: Los usuarios fueron obtenidos satisfactoriamente de la base de datos
        '500':
          description: Error interno del servidor, usualmente generado por una consulta defectuosa o un fallo en la conexión de datos
